Class SW {
    ;; Software class
    static PARENT := "MSDAC Systems"
    static AUTHOR := ["Ken Verdadero", "Reynald Ycong"]
    static NAME := "Hymnal Browser Lite"
    static VERSION := "0.1.0"
    static NAME_VERSION := this.NAME " v" this.VERSION
    static FULLNAME_VERSION := this.PARENT " " this.NAME " v" this.VERSION
    static TITLE := this.NAME
    static SIZE := [340, 85]
    static FILE_ICON := "res\app_icon.ico"
}