/*
    Statistical Data for HBL
    --------------------------------
    Handles hmyn data such as hymn launches, queries, frequency, and suggested data.
    This connects to session data in which the session's data will be forwarded
    in this class for dumping.

    The stats data utilizes JSON for data storage.
    All hymn stats are stored in a JSON file which will be sent to the cloud for analytics.

    (c) 2022 Ken Verdadero, Reynald Ycong
    Written 2022-06-10
*/

class Stats {

}